spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/home
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#    date-format: java.text.SimpleDateFormat
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql


server:
  port: 9090